name: Android CI

on:
  push:
    branches: [ banchorx-main ]
  pull_request:
    branches: [ banchorx-main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build apk
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: build

    - name: Assemble Release APK
      run: ./gradlew assembleRelease

    - name: Pack the APK
      uses: actions/upload-artifact@v4
      with:
        name: odr-bancho
        path: /build/outputs/apk/release/app-release.apk
